export default {
  stepper: undefined,
  newProfileStatus: false,
  analisys: {
    profileId: undefined,
    profileName: undefined,
    personalData: {
      name: undefined,
      sex: undefined,
      race: undefined,
      birthDate: new Date().toISOString().slice(0, 10),
      nationality: undefined,
      deficiency: undefined,
    },
    studentData: {
      ticket: undefined,
      university: undefined,
      location: undefined,
      course: undefined,
      socialSupport: undefined,
      school: undefined,
      semester: undefined,
      parfor: undefined,
      financing: undefined,
      extraCurricular: [],
      reservation: [],
      scholarship: [],
    },
  },
};
